// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhfB_xqs4h1HWimkrO13r8cvnoSJfevbI',
    appId: '1:239816000582:web:64f5ae8d22b83d7fd0b647',
    messagingSenderId: '239816000582',
    projectId: 'notification-e26ce',
    authDomain: 'notification-e26ce.firebaseapp.com',
    storageBucket: 'notification-e26ce.appspot.com',
    measurementId: 'G-FY6PVQ5GJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyg57N-BJDzIk1Qhm-PSlPFLVK0Dy8wHs',
    appId: '1:239816000582:android:8fb44e858edcdb2cd0b647',
    messagingSenderId: '239816000582',
    projectId: 'notification-e26ce',
    storageBucket: 'notification-e26ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAme4amQZa2LM-VLo_ljUPC0Pd2MpNfeyY',
    appId: '1:239816000582:ios:25aec4700e874901d0b647',
    messagingSenderId: '239816000582',
    projectId: 'notification-e26ce',
    storageBucket: 'notification-e26ce.appspot.com',
    iosClientId: '239816000582-o0tkpbo6a2hvm7eb8ar17jspc613jcrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondTaskDharmishtha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAme4amQZa2LM-VLo_ljUPC0Pd2MpNfeyY',
    appId: '1:239816000582:ios:25aec4700e874901d0b647',
    messagingSenderId: '239816000582',
    projectId: 'notification-e26ce',
    storageBucket: 'notification-e26ce.appspot.com',
    iosClientId: '239816000582-o0tkpbo6a2hvm7eb8ar17jspc613jcrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondTaskDharmishtha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhfB_xqs4h1HWimkrO13r8cvnoSJfevbI',
    appId: '1:239816000582:web:7055ed63b82afa7fd0b647',
    messagingSenderId: '239816000582',
    projectId: 'notification-e26ce',
    authDomain: 'notification-e26ce.firebaseapp.com',
    storageBucket: 'notification-e26ce.appspot.com',
    measurementId: 'G-L6YG8W7TCL',
  );

}